### ISSUE TITLE
MinDataBytes only checked in DataPortFile

### ISSUE THREAD

**Issue by CFTechno** [serbod/dataport#10]
Only the DataportFile implementation of **OnIncomingMsgHandler** checks for the length of the data and the **FMinDataBytes** value (around line 220)

`      if Cardinal(Length(sReadData)) >= FMinDataBytes then
      begin
        if Assigned(FOnDataAppear) then
          FOnDataAppear(self);
      end;
`

Please note that this implementation does call **OnDataAppear** unlike DataPortFTDI and DataportUART (see issue #9 )

**Comment by serbod** [comment]
Fixed for DataPortUART and DataPortFTDI.
