### ISSUE TITLE
FTDI  the read routine FT_READ reads the incorrect amount of bytes

### ISSUE THREAD

**Issue by CFTechno** [serbod/dataport#11]
the line (~418) in **DataPortFTDI** 
`        FFtIOStatus := FT_Read(FFtHandle, @FFtInBuffer, ReadCount, @ReadResult);`
will cause read problems with large data transfers in blocks. Also according to the programming manual (version 1.4) 

"FT_STATUS FT_Read (FT_HANDLE ftHandle, LPVOID lpBuffer, DWORD dwBytesToRead,
LPDWORD lpdwBytesReturned)
....
This function does not return until dwBytesToRead bytes have been read into the buffer."

I propose to change the line into
`        FFtIOStatus := FT_Read(FFtHandle, @FFtInBuffer, FFtRxQBytes, @ReadResult);
`

Tested this and the issues i had with not receiving any data after a few bytes are solved with this patch. Using a C232HD cable

**Comment by serbod** [comment]
Fixed. Thanks for reporting!

**Comment by CFTechno** [comment]
Thanks. Nice component!
