### ISSUE TITLE
Convert Stop Bits string to Enumerator StopBits

### ISSUE THREAD

**Issue by eldonfsr** [serbod/dataport#12]
Hello i save config of serial port on xml file to load when app start, I save the values as string for stopbits as stb1 or stb15 but when i try to assign to port send me error 

like this FormMain.DPSerial.StopBits:= CBStopBits.Text;

how i can convert or assign value saved on file xml

Thanks hope can help me...

**Comment by serbod** [comment]
Use Open('COM1,115200,8,N,1')
where 1 for 1 stop bits
You can compose initialization string from parameters

**Comment by eldonfsr** [comment]
Thanks let  me do changes,,
I  have  another  question on DataSerialPort.pas  there  a function SendString but when  try to call that DataPort.SendString
is  not  showing   there  how i can use that function to send string on terminal push  send character  typed on terminal or memo...

**Comment by serbod** [comment]
Please, look for terminal emulator example in "demo" folder

**Comment by eldonfsr** [comment]
Ok Thanks.... sorry for question...
