### ISSUE TITLE
Not Open serial port

### ISSUE THREAD

**Issue by KikePie** [serbod/dataport#14]
I can't connect serial port using this string configuration
InitStr = 'COM4,9600,8,N,1,0,1'
 is correct or i miss something

**Comment by serbod** [comment]
Try 'COM4,9600,8,N,1'
Hardware/Software flow control used for full-speed data transfer for phone line modems and rarely used nowadays.

Also, try another bitrate and port name. Port names can be obtained with TDataPortSerial.GetSerialPortNames()
