### ISSUE TITLE
DataPortSerial.pas cannot find libc (Lazarus / FPC 64-bit linux)

### ISSUE THREAD

**Issue by WayneSherman** [serbod/dataport#3]
Tested on Xubuntu 16.04 64-bit.
Error:  Cannot find unit libc.

According to [FPC wiki](http://wiki.freepascal.org/libc_unit):
> The libc unit is deprecated, and frozen in time for Kylix compatibility, and won't be ported to other architectures or operating systems. 

I don't have a 32-bit test environment, but it works on 64-bit to do this:
```
uses
  {$IFDEF FPC}
    {$DEFINE NO_LIBC}
  {$ENDIF}
```

**Comment by serbod** [comment]
Fixed!
