### ISSUE TITLE
DataPortSerial.pas identifier not found (Lazarus / FPC 64-bit linux) 

### ISSUE THREAD

**Issue by WayneSherman** [serbod/dataport#4]
Tested on Xubuntu 16.04 64-bit.
DataPortSerial.pas Error: Identifier not found "s"

Fixed by adding conditional variable definition:

```
procedure TDataPortSerial.Open(const AInitStr: string = '');
{$IFDEF UNIX}
var
  s: string;
{$ENDIF}
begin

```

**Comment by serbod** [comment]
Thanks for you feedback, it will be fixed.

**Comment by serbod** [comment]
Fixed!
