### ISSUE TITLE
FTDI implementation does not call onDataAppear

### ISSUE THREAD

**Issue by CFTechno** [serbod/dataport#9]
The FTDI implementation will execute in the FTDIClient a check onDataAppear around line 425
`          if Assigned(FParentDataPort.OnDataAppear) then
            Synchronize(SyncProc)
`
this will lead to (around line 593
`      if Assigned(OnIncomingMsgEvent) then
        OnIncomingMsgEvent(self, FRxData);
`

**OnIncomingMsgEvent**  is implemented in **dataportUART** (the parent) and executes
`      if Assigned(OnDataAppearUnsafe) then
        OnDataAppearUnsafe(Self);
`

As an consequence OnDataAppear is never called.

**Comment by CFTechno** [comment]
Temp. workaround was to set OnDataAppearUnsafe to the same callback as OnDataAppear

**Comment by serbod** [comment]
Fixed. Sorry, I can't test it properly because have no serial hardware at that moment. If propblem not gone, feel free to report again.

**Comment by CFTechno** [comment]
Will test and let you know, will have some time next week to do that

**Comment by CFTechno** [comment]
Tested and can confirm working . Thank you.
